### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tom-krusch** [tvoelkel/ICAOcheck#1]
kp wieso aber ich bekomm folgenden Fehler:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "E:\Users\krusc\github\GUI.py", line 77, in load_files
    self.display_result(self.file_list[0])
  File "E:\Users\krusc\github\GUI.py", line 142, in display_result
    self.expression_type_label.set(str(matchableImg.matching_type_list[0]))
IndexError: list index out of range`

ich weiß nicht wieso vielleicht kann da jemand mal gucken

**Comment by PatrickLiedtke** [comment]
Der error kommt bei mir auch. 

Ich vermute, es könnte mit Dateien zusammenhängen, die kein Bild sind

**Comment by PatrickLiedtke** [comment]
Eben nochmal getestet mit einen Ordner wo nur Bilder drin waren, da gab es kein Fehler
